# Merge Excel Files from Scraping Project

In [16]:
import pandas as pd
from IPython.display import display

#### Import Excel Files into List of Files

In [20]:
# Path for Excel Files on Local Machine:
path = "C:/Users/fucac/Documents/projects/realEstateScraping"

fileList = []

# Append .xlsx files to fileList
fileList.append(path + "/Georgia/GA - RealEstateData.xlsx")
fileList.append(path + "/North Carolina/NC - RealEstateData.xlsx")
fileList.append(path + "/South Carolina/SC - RealEstateData.xlsx")
fileList.append(path + "/West Virginia/WV - RealEstateData.xlsx")
fileList.append(path + "/Tennessee/TN - RealEstateData.xlsx")

# Check File List
display(fileList)

# Create a List for Excel
excelList = []

# Read Excel Files into Excel List Via Pandas
for file in fileList:
    excelList.append(pd.read_excel(file))

# Check Excel List
display(excelList)

# Create a Data Frame for ExcelList
realEstateRegional = pd.DataFrame()

# Add to Data Frame with Concat; *Append is Deprecated*
for excelFile in excelList:
    realEstateRegional = realEstateRegional.append(excelFile)

display(realEstateRegional)

['C:/Users/fucac/Documents/projects/realEstateScraping/Georgia/GA - RealEstateData.xlsx',
 'C:/Users/fucac/Documents/projects/realEstateScraping/North Carolina/NC - RealEstateData.xlsx',
 'C:/Users/fucac/Documents/projects/realEstateScraping/South Carolina/SC - RealEstateData.xlsx',
 'C:/Users/fucac/Documents/projects/realEstateScraping/West Virginia/WV - RealEstateData.xlsx',
 'C:/Users/fucac/Documents/projects/realEstateScraping/Tennessee/TN - RealEstateData.xlsx']

[         Price Beds Baths   Square_Feet              Type  \
 0     $250,000  3bd   2ba          1440             House
 1     $299,900  3bd   2ba          2436             House
 2     $299,000  3bd   1ba            --             House
 3     $245,000  2bd   2ba          1128             House
 4     $379,000  3bd   2ba          1657             House
 ...        ...  ...   ...           ...               ...
 1555  $324,900  3bd   3ba          1810  New construction
 1556  $150,000    0     0  0.35acreslot              Land
 1557  $369,900  2bd   2ba            --  New construction
 1558  $319,000  2bd   2ba          1288  New construction
 1559  $165,000    0     0  1.21acreslot              Land

                                             Address
 0        64 Hummingbird Valley, Dahlonega, GA 30533
 1               316 Fortner Dr, Dahlonega, GA 30533
 2          890 Jim Anderson Rd, Dahlonega, GA 30533
 3            3296 Highway 19 N, Dahlonega, GA 30533
 4                98 W Woods Dr, Dahlonega, GA 30533
 ...                                             ...
 1555  242 Quail Forest Cir LOT 32, Toccoa, GA 30577
 1556               55 Currahee Ct, Toccoa, GA 30577
 1557        15 Cottage Ln APT 102, Toccoa, GA 30577
 1558           17 Cottage Ln #102, Toccoa, GA 30577
 1559           13 Edgewater Trl S, Toccoa, GA 30577

 [1560 rows x 6 columns],
         Price Beds Baths   Square_Feet              Type  \
 0    $540,000  4bd   4ba          3175             House
 1    $270,000  3bd   2ba          1488             House
 2    $625,000  4bd   4ba          4194             House
 3    $599,900  5bd   4ba            --             House
 4    $250,000  3bd   2ba          1552             House
 ..        ...  ...   ...           ...               ...
 325  $645,000  2bd   3ba          2503  New construction
 326  $118,771    0     0  5.94acreslot              Land
 327  $565,000  3bd   3ba          2243             House
 328  $550,000  4bd   3ba          2674         Townhouse
 329  $975,000  3bd   4ba          2900  New construction

                                           Address
 0                6002 Windsor Cir, Elon, NC 27244
 1            2449 Moss Creek Loop, Elon, NC 27244
 2           106 Old Charleston Dr, Elon, NC 27244
 3                8012 Windsor Way, Elon, NC 27244
 4                   314 Sunset Dr, Elon, NC 27244
 ..                                            ...
 325    129 Glenbrook Dr, Hendersonville, NC 28739
 326  0 Apple Blossom Rd, Hendersonville, NC 28739
 327        4 Summit Cir, Hendersonville, NC 28739
 328  103 Valley Hill Dr, Hendersonville, NC 28791
 329  152 Spruce Hill Dr, Hendersonville, NC 28792

 [330 rows x 6 columns],
         Price Beds Baths Square_Feet              Type  \
 0    $475,000  3bd   4ba          --  New construction
 1    $385,000  3bd   3ba          --             House
 2    $359,900  4bd   3ba          --             House
 3    $398,000  2bd   1ba          --             House
 4    $299,900  3bd   2ba          --             House
 ..        ...  ...   ...         ...               ...
 392  $485,000  3bd   2ba        1175             House
 393  $419,900  4bd   3ba        2302             House
 394  $309,900  3bd   2ba        1620             House
 395  $450,990  5bd   3ba        3053  New construction
 396  $225,000  3bd   2ba        1123             House

                                            Address
 0              6 Vest St, Travelers Rest, SC 29690
 1        112 E Scenic Ln, Travelers Rest, SC 29690
 2          200 Corey Way, Travelers Rest, SC 29690
 3     99 Leaning Tree Ct, Travelers Rest, SC 29690
 4     104 Alta Vista Cir, Travelers Rest, SC 29690
 ..                                             ...
 392   4183 S Rhett Ave, North Charleston, SC 29405
 393   5410 Barnsley Dr, North Charleston, SC 29420
 394          2583 Otranto Rd, Charleston, SC 29406
 395      8807 Citronella Way, Charleston, SC 29406
 396  2008 Cosgrove Ave, North Charleston, SC 29405

 [397 rows x 6 columns],
         Price Beds Baths Square_Feet               Type  \
 0    $295,000  3bd   2ba        2056              House
 1    $250,000  3bd   3ba        3120              House
 2    $309,000  4bd   3ba        2130              House
 3    $194,000  3bd   2ba        1148              House
 4    $319,000  5bd   4ba        3360              House
 ..        ...  ...   ...         ...                ...
 355   $60,000  2bd   2ba         715              House
 356  $341,999  4bd   3ba        2216   New construction
 357   $49,900  4bd   2ba        1872  Multi-family home
 358   $37,500  2bd   1ba         982              House
 359   $18,000  3bd   1ba        1200              House

                                        Address
 0    379 Tyrone Avery Rd, Morgantown, WV 26508
 1      81 Cherry Hill Rd, Morgantown, WV 26508
 2          253 Morris St, Morgantown, WV 26501
 3          608 Morgan St, Morgantown, WV 26505
 4          866 Beulah Rd, Morgantown, WV 26508
 ..                                         ...
 355            1014 Fay St, Fairmont, WV 26554
 356         0 Eastview Way, Fairmont, WV 26554
 357            108 Paul Ave, Weirton, WV 26062
 358         223 Franklin St, Weirton, WV 26062
 359           108 N 12th St, Weirton, WV 26062

 [360 rows x 6 columns],
          Price       Beds Baths   Square_Feet   Type  \
 0     $699,900        3bd   2ba          2132  House
 1     $799,900        3bd   3ba          2482  House
 2     $899,900        4bd   3ba          3290  House
 3     $749,900        4bd   3ba          2455  House
 4     $360,000        2bd   1ba          1008  House
 ...        ...        ...   ...           ...    ...
 2090  $459,900        3bd   3ba          2300    NaN
 2091  $245,000        3bd   2ba          1148    NaN
 2092  $299,900          0     0  21.7acreslot    NaN
 2093  $399,000        3bd   3ba          2009    NaN
 2094  $399,900  Studio2ba  4288         House    NaN

                                         Address
 0            110 Foxwood Ln, Franklin, TN 37069
 1        1606 Callie Way Dr, Franklin, TN 37064
 2         620 Rutherford Ln, Franklin, TN 37064
 3          501 Ridgewood Rd, Franklin, TN 37064
 4     1200 Carriage Park Dr, Franklin, TN 37064
 ...                                         ...
 2090                                        NaN
 2091                                        NaN
 2092                                        NaN
 2093                                        NaN
 2094                                        NaN

 [2095 rows x 6 columns]]

C:\Users\fucac\AppData\Local\Temp\ipykernel_18176\2484682932.py:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  realEstateRegional = realEstateRegional.append(excelFile)
C:\Users\fucac\AppData\Local\Temp\ipykernel_18176\2484682932.py:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  realEstateRegional = realEstateRegional.append(excelFile)
C:\Users\fucac\AppData\Local\Temp\ipykernel_18176\2484682932.py:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  realEstateRegional = realEstateRegional.append(excelFile)

,Price,Beds,Baths,Square_Feet,Type,Address
0,"$250,000",3bd,2ba,1440,House,"64 Hummingbird Valley, Dahlonega, GA 30533"
1,"$299,900",3bd,2ba,2436,House,"316 Fortner Dr, Dahlonega, GA 30533"
2,"$299,000",3bd,1ba,--,House,"890 Jim Anderson Rd, Dahlonega, GA 30533"
3,"$245,000",2bd,2ba,1128,House,"3296 Highway 19 N, Dahlonega, GA 30533"
4,"$379,000",3bd,2ba,1657,House,"98 W Woods Dr, Dahlonega, GA 30533"
...,...,...,...,...,...,...
2090,"$459,900",3bd,3ba,2300,NaN,NaN
2091,"$245,000",3bd,2ba,1148,NaN,NaN
2092,"$299,900",0,0,21.7acreslot,NaN,NaN
2093,"$399,000",3bd,3ba,2009,NaN,NaN
2094,"$399,900",Studio2ba,4288,House,NaN,NaN

#### Export to Excel File

In [21]:
# Create an export to Excel File for Furthur Analysis

# Create File Name
fileName = 'Regional - RealEstateData.xlsx'

# Export to Excel; Sheet Named: 'Real Estate Data';
with pd.ExcelWriter(fileName, engine="openpyxl", mode="w") as writer:
    realEstateRegional.to_excel(writer, 'Regional - Real Estate Data', index=False)